version: "3.8"

services:
  rabbitmq:
    image: masstransit/rabbitmq:latest
    ports:
     - "5672:5672"
     - "15672:15672"
     - "15692:15692"

  openweather:
    image: ${DOCKER_REGISTRY-}openweather
    restart: on-failure
    build:
      context: .
      dockerfile: Services/Weather/OpenWeather.API/Dockerfile
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80

  playlist:
    image: ${DOCKER_REGISTRY-}playlist
    restart: on-failure
    build:
      context: .
      dockerfile: Services/Playlist/Playlist.API/Dockerfile
    ports:
      - "5002:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
