version: "3.8"

services:
  rabbitmq:
    image: masstransit/rabbitmq:latest
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 5s
      timeout: 15s
      retries: 1
    networks:
        - rabbitmq_go_net

  openweather:
    image: ${DOCKER_REGISTRY-}openweather
    restart: on-failure
    build:
      context: .
      dockerfile: Services/Weather/OpenWeather.API/Dockerfile
    ports:
      - 5001:80
    networks:
      - rabbitmq_go_net
    depends_on:
      rabbitmq:
        condition: service_healthy

  playlist:
    image: ${DOCKER_REGISTRY-}playlist
    restart: on-failure
    build:
      context: .
      dockerfile: Services/Playlist/Playlist.API/Dockerfile
    ports:
      - 5002:80
    networks:
        - rabbitmq_go_net
    depends_on:
      rabbitmq:
        condition: service_healthy

networks:
  rabbitmq_go_net:
    driver: bridge